# Generated by Django 2.2.17 on 2020-11-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='氏名')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='年齢')),
                ('birthday', models.DateField(blank=True, verbose_name='誕生日')),
                ('hiredate', models.DateField(blank=True, verbose_name='入社日')),
                ('retiredate', models.DateField(blank=True, verbose_name='退社日')),
                ('createddate', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('lastmodifieddate', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
            ],
        ),
    ]
