# Generated by Django 2.2.17 on 2020-11-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='誕生日'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hiredate',
            field=models.DateField(blank=True, null=True, verbose_name='入社日'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='retiredate',
            field=models.DateField(blank=True, null=True, verbose_name='退社日'),
        ),
    ]
